#!/usr/bin/env python3
"""Generate the PDF glyph and encoding tables in internal/pdf/extract.

Run it through go generate (see internal/pdf/extract/gen.go):

    go generate ./internal/pdf/extract/

or directly from any directory:

    python3 tools/gen_tables.py

Outputs and their sources:

  tables_base14.go    pdf-inspector src/extractor/base14.rs
  tables_glyphs.go    pdf-inspector src/glyph_names.rs
  tables_stdenc.go    lopdf src/encodings/mappings.rs (STANDARD_ENCODING)
  tables_encoding.go  Python's built-in cp1252 and mac_roman codecs

The sources are pinned. pdf-inspector is a git checkout of UPSTREAM_REPO at
UPSTREAM_COMMIT. Clone it into reference/pdf-inspector (gitignored), or point
DOCSTOMD_TABLES_SRC at its src/ directory. lopdf is the crates.io release
LOPDF_VERSION, the version pdf-inspector's Cargo.lock pins at that commit.
Running `cargo fetch` in the checkout puts it in the Cargo registry, or point
DOCSTOMD_LOPDF_SRC at its src/ directory. Both projects are MIT-licensed; see
NOTICE.md.

The script stops if the pdf-inspector checkout is at a different commit.
Set DOCSTOMD_TABLES_ALLOW_UNPINNED=1 to run against it anyway, for example
when checking what a newer upstream would change.

gofmt must be on PATH or in $GOROOT/bin. go generate sets GOROOT.
"""
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

UPSTREAM_REPO = "https://github.com/firecrawl/pdf-inspector"
UPSTREAM_COMMIT = "d8da3b44c57d807cdbca5aa31d4c0e14d9ee3aae"
LOPDF_VERSION = "0.44.0"

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "internal" / "pdf" / "extract"
SRC = Path(os.environ.get("DOCSTOMD_TABLES_SRC") or ROOT / "reference" / "pdf-inspector" / "src")


def fail(msg):
    raise SystemExit(f"gen_tables: {msg}")


def check_pin():
    if not SRC.is_dir():
        fail(
            f"pdf-inspector source not found at {SRC}\n"
            f"  git clone {UPSTREAM_REPO} reference/pdf-inspector\n"
            f"  git -C reference/pdf-inspector checkout {UPSTREAM_COMMIT}\n"
            "or set DOCSTOMD_TABLES_SRC to its src/ directory"
        )
    try:
        head = subprocess.run(
            ["git", "-C", str(SRC), "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        print(f"gen_tables: warning: cannot read the git commit of {SRC}; "
              f"make sure it matches {UPSTREAM_COMMIT}", file=sys.stderr)
        return
    if head == UPSTREAM_COMMIT:
        return
    msg = f"{SRC} is at commit {head}, but the pinned commit is {UPSTREAM_COMMIT}"
    if os.environ.get("DOCSTOMD_TABLES_ALLOW_UNPINNED") == "1":
        print(f"gen_tables: warning: {msg}", file=sys.stderr)
        return
    fail(msg + "\n(set DOCSTOMD_TABLES_ALLOW_UNPINNED=1 to generate from it anyway)")


def lopdf_src():
    override = os.environ.get("DOCSTOMD_LOPDF_SRC")
    if override:
        return Path(override)
    lock = SRC.parent / "Cargo.lock"
    if lock.is_file():
        m = re.search(r'name = "lopdf"\nversion = "([^"]+)"', lock.read_text())
        if m and m.group(1) != LOPDF_VERSION:
            fail(f"{lock} pins lopdf {m.group(1)}, but this script expects {LOPDF_VERSION}")
    cargo_home = Path(os.environ.get("CARGO_HOME") or Path.home() / ".cargo")
    for d in sorted((cargo_home / "registry" / "src").glob(f"*/lopdf-{LOPDF_VERSION}/src")):
        return d
    fail(
        f"lopdf {LOPDF_VERSION} source not found under {cargo_home}/registry/src\n"
        "  run `cargo fetch` in the pdf-inspector checkout, "
        "or set DOCSTOMD_LOPDF_SRC to lopdf's src/ directory"
    )


def gofmt_path():
    found = shutil.which("gofmt")
    if found:
        return found
    goroot = os.environ.get("GOROOT")
    if goroot and (Path(goroot) / "bin" / "gofmt").is_file():
        return str(Path(goroot) / "bin" / "gofmt")
    fail("gofmt not found on PATH or in $GOROOT/bin")


def write_go(name, header, body_lines):
    src = "\n".join([f"// Code generated by tools/gen_tables.py {header}. DO NOT EDIT.", "",
                     "package extract", "", *body_lines])
    formatted = subprocess.run(
        [gofmt_path()], input=src, capture_output=True, text=True,
    )
    if formatted.returncode != 0:
        fail(f"gofmt rejected {name}:\n{formatted.stderr}")
    (OUT / name).write_text(formatted.stdout)


def rust_char_to_go(lit):
    if lit.startswith("\\u{"):
        cp = int(lit[3:-1], 16)
        return f"0x{cp:04X}"
    if lit.startswith("\\u"):
        cp = int(lit[2:6], 16)
        return f"0x{cp:04X}"
    if lit.startswith("\\") and len(lit) == 2:
        return {
            "\\": "0x5C",
            "'": "0x27",
            '"': "0x22",
            "n": "0x0A",
            "r": "0x0D",
            "t": "0x09",
            "0": "0x00",
        }.get(lit[1], None) or f"0x{ord(lit[1]):04X}"
    return f"0x{ord(lit):04X}"


def gen_base14():
    text = (SRC / "extractor" / "base14.rs").read_text()
    out = []
    aliases = {}
    for m in re.finditer(r"static (\w+): &\[\(char, u16\)\] = (\w+);", text):
        aliases[m.group(1)] = m.group(2)
    for m in re.finditer(r"static (\w+): &\[\(char, u16\)\] = &\[(.*?)\];", text, re.S):
        name, body = m.group(1), m.group(2)
        pairs = re.findall(r"'((?:\\.|[^'])*)',\s*(\d+)", body)
        if not pairs:
            continue
        entries = ", ".join(f"{{rune({rust_char_to_go(c)}), {w}}}" for c, w in pairs)
        out.append(f"var base14{name} = []charWidth{{{entries}}}")
        out.append("")
    for m in re.finditer(r"static (\w+): &\[\(u8, char\)\] = &\[(.*?)\];", text, re.S):
        name, body = m.group(1), m.group(2)
        pairs = re.findall(r"0x([0-9A-Fa-f]{2}),\s*'((?:\\.|[^'])*)'\)", body)
        if not pairs:
            continue
        entries = ", ".join(f"{{0x{b}, rune({rust_char_to_go(c)})}}" for b, c in pairs)
        goname = "symbolEncodingTable" if "SYMBOL" in name else "zapfEncodingTable"
        out.append(f"var {goname} = []codeChar{{{entries}}}")
        out.append("")
    for alias, target in aliases.items():
        out.append(f"var base14{alias} = base14{target}")
        out.append("")
    write_go("tables_base14.go", "from pdf-inspector src/extractor/base14.rs", out)


def gen_glyphs():
    text = (SRC / "glyph_names.rs").read_text()
    pairs = re.findall(
        r'm\.insert\("([^"]+)",\s*\'((?:\\u\{[0-9A-Fa-f]+\}|\\.|[^\\\']))\'\);', text
    )
    seen = {}
    for name, ch in pairs:
        seen[name] = ch
    out = ["var glyphToUnicode = map[string]rune{"]
    for name in sorted(seen):
        out.append(f'\t"{name}": rune({rust_char_to_go(seen[name])}),')
    out.append("}")
    out.append("")
    write_go("tables_glyphs.go", "from pdf-inspector src/glyph_names.rs", out)


def gen_stdenc(lopdf):
    text = (lopdf / "encodings" / "mappings.rs").read_text()
    m = re.search(r"pub const STANDARD_ENCODING: CodedCharacterSet = \[(.*?)\];", text, re.S)
    if not m:
        fail("STANDARD_ENCODING not found in lopdf mappings.rs")
    items = [x.strip() for x in m.group(1).split(",") if x.strip()]
    if len(items) != 256:
        fail(f"STANDARD_ENCODING has {len(items)} entries, want 256")
    out = ["var standardEncodingNames = map[byte]string{"]
    for code, item in enumerate(items):
        if item == "None":
            continue
        g = re.fullmatch(r"Some\(Glyph::(\w+)\)", item)
        if not g:
            fail(f"unexpected STANDARD_ENCODING entry {item!r}")
        out.append(f'\t{code}: "{g.group(1)}",')
    out += [
        "}",
        "",
        "var standardEncoding = func() map[byte]rune {",
        "\tm := make(map[byte]rune, len(standardEncodingNames))",
        "\tfor b, name := range standardEncodingNames {",
        "\t\tm[b] = glyphToChar(name)",
        "\t}",
        "\treturn m",
        "}()",
        "",
    ]
    write_go("tables_stdenc.go", f"from lopdf {LOPDF_VERSION} STANDARD_ENCODING", out)


def codec_table(goname, codec, codes):
    out = [f"var {goname} = map[byte]rune{{"]
    for code in codes:
        try:
            ch = bytes([code]).decode(codec)
        except UnicodeDecodeError:
            continue
        out.append(f"\t{code}: rune(0x{ord(ch):04X}),")
    out.append("}")
    out.append("")
    return out


def gen_encoding():
    out = codec_table("winAnsiEncoding", "cp1252", range(256))
    out += codec_table("macRomanEncoding", "mac_roman", range(256))
    out += codec_table("cp1252High", "cp1252", range(0x80, 256))
    write_go("tables_encoding.go", "from Python's cp1252 and mac_roman codecs", out)


if __name__ == "__main__":
    check_pin()
    lopdf = lopdf_src()
    gen_base14()
    gen_glyphs()
    gen_stdenc(lopdf)
    gen_encoding()
    print("gen_tables: wrote", ", ".join(sorted(p.name for p in OUT.glob("tables_*.go"))))
